# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursetype',
            field=models.CharField(default='strtmp', max_length=50),
            preserve_default=False,
        ),
    ]
