# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0002_course_coursetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(default='nulstr', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='website',
            field=models.URLField(default='nullstr'),
            preserve_default=False,
        ),
    ]
