# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0003_auto_20171029_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
