# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0006_auto_20171104_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='overallrate',
        ),
        migrations.AddField(
            model_name='rate',
            name='D_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='A_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='B_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='C_score',
            field=models.FloatField(default=0),
        ),
    ]
