# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0007_auto_20171105_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='term',
            field=models.CharField(default='hahaha', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='total_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
