# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0009_comment_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(),
        ),
    ]
