# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0010_auto_20171106_1246'),
        ('rateMyCourse', '0011_hitcount'),
    ]

    operations = [
    ]
